/*
 * Happy Primes
 */
void errExit(const char *func) {
    perror(func);
    exit(EXIT_FAILURE);
}
